export const REQUEST_HOME_PAGE_IMAGE = 'REQUEST_HOME_PAGE_IMAGE';
export const RECEIVE_HOME_PAGE_IMAGE = 'RECEIVE_HOME_PAGE_IMAGE';
export const REQUEST_HOME_PAGE_PROMO = 'REQUEST_HOME_PAGE_PROMO';
export const RECEIVE_HOME_PAGE_PROMO = 'RECEIVE_HOME_PAGE_PROMO';
